spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  application:
    name: nz-market-backend
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/market}
    username: ${DB_USER:market}
    password: ${DB_PASSWORD:market}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: ${TZ:Pacific/Auckland}
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    nz.co.market: ${LOG_LEVEL:INFO}
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Application specific configuration
app:
  jwt:
    secret: ${JWT_SECRET:Y2hhbmdlX21lX2luX3Byb2R1Y3Rpb25fYW5kX3VzZV9hX3NlY3VyZV9rZXlfaGVyZQ==}
    access-token-expiration: 900000 # 15 minutes
    refresh-token-expiration: 604800000 # 7 days
  
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  
  s3:
    endpoint: ${S3_ENDPOINT:http://localhost:9000}
    bucket: ${S3_BUCKET:market-uploads}
    access-key: ${S3_ACCESS_KEY:minio}
    secret-key: ${S3_SECRET_KEY:minio_secret}
    region: ${S3_REGION:us-east-1}
    max-file-size: 5242880 # 5MB
  
  stripe:
    secret-key: ${STRIPE_SECRET_KEY:sk_test_xxx}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_xxx}
    publishable-key: ${STRIPE_PUBLISHABLE_KEY:pk_test_xxx}
  
  currency:
    default: ${CURRENCY:NZD}
    symbol: ${CURRENCY_SYMBOL:$}
  
  tax:
    enabled: ${TAX_ENABLED:false}
    rate: ${TAX_RATE:0.15} # 15% GST for NZ
  
  timezone: ${TZ:Pacific/Auckland}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
